/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planetprogrammig;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URI;
import javax.swing.ImageIcon;
import recursos.Mensaje;

/**
 *
 * @author kevin2
 */
public class VtnAcercaDe extends javax.swing.JDialog {

    /**
     * Creates new form AcercaDe
     * @param parent designa a quien esta heredando la ventana
     * @param modal es un booleano que dice que si se mueve el cursor a otra parte este tendra que cerrarse esta ventana para que se pueda ver otra parte
     */
    public VtnAcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Acerca del Planet editor");
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/planetUrano.png"));
        this.setIconImage(icono);
        setLocationRelativeTo(this);
        ImageIcon imagenP = new ImageIcon(ClassLoader.getSystemResource("imagenes/planetUrano.png"));
        ImageIcon imagent = new ImageIcon(ClassLoader.getSystemResource("iconos/tecnologico.png"));
        jLabel2.setIcon(new ImageIcon(imagenP.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH)));
        jLabel3.setIcon(new ImageIcon(imagent.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH)));
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/planetUrano.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Este software es un editor de código, que sirve como un compilador con el plus de ejecutar el mismo código sin \nrepresentar daños o grandes cambiospara una aplicación, y además de sertambién una herramienta para el \nprogramador al momento de crear su propio lenguaje de programación. \n\n\n\n\n\n\n\n         Programado por:\n Kevin Ivan Sanchez Valdin");
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/4202011 - email gmail logo mail social social media.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/4202098 - code developer github logo.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/4202110 - facebook logo social social media.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 255));
        jLabel4.setText("/Cat-KevinSanchez");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("/Kevin Ivan Sanchez Valdin");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("/kevinSanchez999@Outlook.com");

        panel1.setColorPrimario(new java.awt.Color(0, 102, 102));
        panel1.setColorSecundario(new java.awt.Color(0, 102, 102));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/tecnologico.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Planet Editor");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.gmail.com/"));
        } catch (Exception e) {
            Mensaje.error(null, "Ocurrio un error...");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.github.com/"));
        } catch (Exception e) {
            Mensaje.error(null, "Ocurrio un error...");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/kevinivansanchezvaldin3/"));
        } catch (Exception e) {
            Mensaje.error(null, "Ocurrio un error...");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VtnAcercaDe dialog = new VtnAcercaDe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
/*
Sintactico

 */
 /**
        Lexico objLex = new Lexico();
        Lexico objLex2 = new Lexico();
        String cadena = "";
        System.out.println("2");
        for (int i = 0; i < vecSal.length; i++) {
            cadena = cadena + vecSal[i] + " ";

        }
        System.out.println("3");
        cadena = cadena + " $";
        txtPanelCompilando.setText(cadena);
        txtPanelCompilando.setText("Movimientos");
        //Otro txtPanel
        //  .setText("Cadena a validar");
        txtPanelSalida.setText("$ 150");

        int mg[][]
                = {{},
                {152, 151},
                {15, 50, 1},
                {13, 153, 12, 50, 3, 2},
                {13, 154, 12, 7, 50, 10, 9, 8, 6, 28, 5, 4, 2},
                {154, 15, 155},
                {},
                {156},
                {157},
                {158},
                {159, 50, 8},
                {159, 50, 19},
                {},
                {160, 161, 16, 50},
                {160, 161, 11},
                {},
                {162},
                {50},
                {51},
                {52},
                {22},
                {23},
                {53},
                {7, 163, 6, 27, 13, 165, 12, 14},
                {164},
                {165, 166},
                {},
                {15, 167, 168, 16, 50},
                {167, 161, 11},
                {},
                {161, 11, 161},
                {169, 161, 17, 161},
                {161, 18},
                {}
                };

        int mt[][] = new int[20][54];

        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 54; j++) {
                mt[i][j] = -1;
            }
        }
        System.out.println("4");
        mt[0][1] = 1;
        mt[1][1] = 2;
        mt[2][2] = 3;
        mt[3][2] = 4;
        mt[4][8] = 5;
        mt[4][14] = 5;
        mt[4][50] = 5;
        mt[4][13] = 6;
        mt[5][8] = 6 + 1;
        mt[5][14] = 8 + 1;
        mt[5][50] = 7 + 1;
        mt[6][8] = 9 + 1;
        mt[7][50] = 12 + 1;
        mt[8][14] = 22 + 1;
        mt[9][15] = 11 + 1;
        mt[9][19] = 10 + 1;
        mt[10][11] = 13 + 1;
        mt[10][15] = 14 + 1;
        mt[11][22] = 15 + 1;
        mt[11][23] = 15 + 1;
        mt[11][50] = 15 + 1;
        mt[11][51] = 15 + 1;
        mt[11][52] = 15 + 1;
        mt[11][53] = 15 + 1;
        mt[12][22] = 19 + 1;
        mt[12][23] = 20 + 1;
        mt[12][50] = 16 + 1;
        mt[12][51] = 17 + 1;
        mt[12][52] = 18 + 1;
        mt[12][53] = 21 + 1;
        mt[13][22] = 15 + 1;
        mt[13][23] = 23 + 1;
        mt[13][50] = 23 + 1;
        mt[13][51] = 23 + 1;
        mt[13][52] = 23 + 1;
        mt[13][53] = 23 + 1;
        mt[14][22] = 30 + 1;
        mt[14][23] = 30 + 1;
        mt[14][50] = 30 + 1;
        mt[14][51] = 30 + 1;
        mt[14][52] = 30 + 1;
        mt[14][53] = 30 + 1;
        mt[15][13] = 25 + 1;
        mt[15][50] = 24 + 1;
        mt[16][50] = 26 + 1;
        mt[17][11] = 27 + 1;
        mt[17][15] = 28 + 1;
        mt[18][22] = 29 + 1;
        mt[18][23] = 29 + 1;
        mt[18][50] = 29 + 1;
        mt[18][51] = 29 + 1;
        mt[18][52] = 29 + 1;
        mt[18][53] = 29 + 1;
        mt[19][7] = 32 + 1;
        mt[19][18] = 31 + 1;

        int vecMov[] = {0, 150};
        int vecMovAux[];
        int i = 0;
        int pr = 0;
        int pc = 0;
        int nl = 0;
        int tv = 0;
        cadena = "";

        do {
            pr = vecMov[vecMov.length - 1];
            if (pr >= 150) {
                pr = pr - 150;
                pc = vecSal[i];
                nl = mt[pr][pc];
                if (nl != -1) {
                    vecMovAux = vecMov;
                    vecMov = new int[(vecMovAux.length + mg[nl].length) - 1];
                    tv = 0;
                    for (int j = 0; j < vecMovAux.length - 1; j++) {
                        vecMov[j] = vecMovAux[j];
                    }
                    System.out.println("5");
                    for (int j = vecMovAux.length - 1; j < vecMov.length; j++) {
                        vecMov[j] = mg[nl][tv];
                        tv++;
                    }
                    System.out.println("6");
                    cadena = txtPanelEditando.getText() + "\n";
                    for (int j = 0; j < vecMov.length; j++) {
                        cadena = cadena + vecMov[j] + " ";
                    }
                    txtPanelEditando.setText(cadena);
                    System.out.println("7");
                    cadena = txtPanelCompilando.getText() + "\n";
                    for (int j = 0; j < vecSal.length; j++) {
                        cadena = cadena + vecSal[j] + " ";
                    }
                    System.out.println("8");
                    cadena = cadena + "$";
                    txtPanelCompilando.setText(cadena);
                } else {
                    objLex = objLex.etiquetar2(vecMov[vecMov.length - 1] + "");
                    objLex2 = objLex.etiquetar2(vecSal[i] + "");
                    if (vecMov[vecMov.length - 1] < 100) {
                        cadena = txtPanelEditando.getText() + "\n Error Sintáctico al recibir " + vecSal[i] + "(" + objLex2.nombre + ")" + " se esperaba " + vecMov[vecMov.length - 1] + "(" + objLex.nombre + ")";
                    } else {
                        cadena = txtPanelEditando.getText() + "\n Error Sintáctico al recibir " + vecSal[i] + "(" + objLex2.nombre + ")" + " se esperaba ";
                    }

                    for (int j = 0; j < 54; j++) {
                        if (mt[pr][j] != -1) {
                            objLex = objLex.etiquetar2(j + "");
                            cadena = cadena + " " + j + "(" + objLex.nombre + ")";
                        }
                    }
                    System.out.println("9");
                    txtPanelEditando.setText(cadena);
                    break;
                }
            } else {
                if (vecSal[i] == vecMov[vecMov.length - 1]) {
                    i++;
                    vecMovAux = vecMov;
                    vecMov = new int[vecMovAux.length - 1];
                    for (int j = 0; j < vecMov.length; j++) {
                        vecMov[j] = vecMovAux[j];

                    }
                    System.out.println("10");
                    cadena = txtPanelEditando.getText() + "\n";
                    for (int j = 0; j < vecMov.length; j++) {
                        cadena = cadena + vecMov[j] + " ";
                    }
                    System.out.println("11");
                    txtPanelEditando.setText(cadena);
                    cadena = txtPanelCompilando.getText() + "\n";
                    for (int j = i; j < vecSal.length; j++) {
                        System.out.println(i);
                        System.out.println(vecMov.length);
                        System.out.println(vecSal.length);
                        cadena = cadena + vecSal[j] + " ";
                    }
                    System.out.println("12");
                    txtPanelCompilando.setText(cadena);
                } else {
                    objLex = objLex.etiquetar2(vecMov[vecMov.length - 1] + "");
                    objLex2 = objLex.etiquetar2(vecSal[i] + "");
                    cadena = txtPanelEditando.getText() + "\n Error sintáctico al recibir " + vecSal[i] + "(" + objLex2.nombre + ")" + " se esperaba " + vecMov[vecMov.length - 1] + "(" + objLex.nombre + ")";
                    txtPanelEditando.setText(cadena);
                    break;
                }

            }
        } while (i < vecSal.length);
        if (vecMov[vecMov.length - 1] == 0) {
            cadena = txtPanelEditando.getText() + "\n Sintácticamente Correcto";
            txtPanelCompilando.setText(cadena);
        }*/
