/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planetprogrammig;

import clases.Automata;
import clases.Lexema;
import clases.Lexico;
import clases.ManipulaArchivos;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import static planetprogrammig.EditorPlanetProgramming.separador;
import recursos.Validaciones;

/**
 *
 * @author por_s
 */
public class VtnEjecutar extends javax.swing.JFrame {

    String texto = "";
    EditorPlanetProgramming ePP;

    int[][] matrizGeneral = {
        {1, 3, 6, 9, 12, 14, 16, 18, 20, 23, 24, 26, -1, -1, -2},
        {2, 1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -2},
        {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -3},
        {-1, 5, 3, -1, -1, -1, -1, -1, 4, -1, -1, -1, -1, -1, -3},
        {-1, -1, -1, -1, -1, -1, -1, -1, 4, -1, -1, -1, -1, -1, -3},
        {-1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -3},
        {-1, 7, 6, -1, -1, -1, -1, -1, 8, -1, -1, -1, -1, -1, -3},
        {-1, -1, 6, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -3},
        {-1, -1, -1, -1, -1, -1, -1, -1, 8, -1, -1, -1, -1, -1, -3},
        {-1, 10, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
        {-1, 10, 10, -1, -1, 11, -1, -1, 10, -1, -1, -1, -1, -1, -3},
        {-1, 10, 10, -1, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1},
        {-1, 13, 13, -1, -1, -1, -1, -1, 13, -1, -1, -1, -1, -1, -1},
        {-1, 13, 13, -1, -1, -1, -1, -1, 13, -1, -1, -1, -1, -1, -3},
        {-1, -1, 15, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1},
        {-1, 15, 15, -1, -1, -1, -1, -1, 15, -1, -1, -1, -1, -1, -1},
        {-1, 17, 17, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -3},
        {-1, 17, 17, -1, -1, -1, -1, -1, 17, -1, -1, -1, -1, -1, -1},
        {-1, 19, 19, -1, -1, -1, -1, -1, 19, -1, -1, -1, -1, -1, -3},
        {-1, 19, 19, -1, -1, -1, -1, -1, 19, -1, -1, -1, -1, -1, -1},
        {-1, -1, -1, -1, -1, -1, -1, -1, 20, -1, -1, -1, -1, 21, -3},
        {-1, -1, -1, -1, -1, -1, -1, -1, 22, -1, -1, -1, -1, -1, -1},
        {-1, -1, -1, -1, -1, -1, -1, -1, 22, -1, -1, -1, -1, -1, -3},
        {-1, -1, -1, -1, -1, -1, -1, -1, 20, -1, -1, -1, -1, -1, -1},
        {-1, 25, 25, -1, -1, -1, -1, -1, 25, -1, -1, -1, -1, -1, -1},
        {-1, 25, 25, -1, -1, -1, -1, -1, 25, -1, -1, -1, -1, -1, -3},
        {-1, 27, 27, -1, -1, -1, -1, -1, 27, -1, -1, -1, 27, -1, -1},
        {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28, -1, -1, -1},
        {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -3}
    };

    char[] alfabeto = {'"', 'A', 'L', '$', '&', '_', '~', '@', 'D', '-', '#', '\'', 'C', '.', '?'};

    /**
     * Creates new form Ejecutar
     */
    public VtnEjecutar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Separador de palabras");
    }

    public EditorPlanetProgramming getePP() {
        return ePP;
    }

    public void setePP(EditorPlanetProgramming ePP) {
        this.ePP = ePP;
    }

    public String getTexto() {
        return texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlTitulo.setBackground(new java.awt.Color(0, 102, 102));

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Analisis léxico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 91, 30));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 106, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Carge el archivo la tabla de transicciones .xlsx ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 22, 420, 29));

        jButton1.setText("Adjuntar archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 63, -1, 30));
        jPanel1.add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, 32));

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        //"+-=*&| {}()[]!?^/%;:.,<>\n\t\r\b\f"
        ArrayList<Integer> palabras = new ArrayList<>();

        Lexico analisisLexico = new Lexico(getTexto(),"()}{,-;:<>=. \t\n\r3", url);
        Automata s = new Automata(getTexto(), analisisLexico.getVecAlfabeto(), analisisLexico.getMatrizTransaccionGeneral());
        s.desCadena();

        s.desVectorAlfabeto();
        s.desMatrizTrasicion();
        ArrayList<Lexema> lexemas = analisisLexico.analisisLexico();
      
        
        String textoMostrar = "";
        for (int i = 0; i < lexemas.size(); i++) {
            textoMostrar += " " + lexemas.get(i).getLexema() + "\t" + lexemas.get(i).getNombreToken() + "\t" + lexemas.get(i).getNumToken() + "\t" + lexemas.get(i).getRenglon() + "\n";
            palabras.add(lexemas.get(i).getNumToken());
        }

        ePP.getTxtPanelCompilando().setText(textoMostrar);

        ManipulaArchivos.guardar(String.valueOf(palabras), ePP.rutaArchivo.substring(0, ePP.rutaArchivo.length() - 4) + "_analisislexico.txt");
        //char[] separador = txtSeparadores.getText().toCharArray();
        //palabras=clases.Separador.separarCodigo(ePP.getTxtPanelCompilando(),getTexto(),txtSeparadores.getText()); 
    
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    String url;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser selecciona = new JFileChooser();  //crea objeto file chooser
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo .xlsx", "xlsx", "xlsx");  //solo muestra archivos .mp3 en file chocer
        selecciona.setFileFilter(filtro);  //se agrega el filtro al file chooser
        selecciona.showOpenDialog(this);   //sin esto me marcaba error :v
        File archivoExtraido = selecciona.getSelectedFile(); //obtiene el archivo en la variable archivo

        String etiquetaNombre;
        if (archivoExtraido != null) // si no se selecciono ningun archivo no hace nada
        {
            try {
                url = archivoExtraido.getCanonicalPath(); //obtiene la ruta del archivo
                etiquetaNombre = archivoExtraido.getName();//obtiene el nombre del arch
                lblTexto.setText(etiquetaNombre);
            } catch (IOException ex) {
                Logger.getLogger(VtnEjecutar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnEjecutar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnEjecutar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnEjecutar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnEjecutar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnEjecutar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
