/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planetprogrammig;

import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;

/**
 *
 * @author kevin2
 */
public class VtnFuente extends javax.swing.JDialog {

    private String fuentes[];
    private DefaultListModel dlmF;
    private DefaultListModel dlmD;
    private DefaultListModel dlmE;
    private String fuente;
    private int dimension;
    private int estilo;
    private int iFont = 0;

    VtnConfiguracion vtnConfig = null;

    /**
     * Creates new form FormatoConfiguracion
     * @param parent designa a quien esta heredando la ventana
     * @param modal es un booleano que dice que si se mueve el cursor a otra parte este tendra que cerrarse esta ventana para que se pueda ver otra parte
     */
    public VtnFuente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/planetUrano.png"));
        this.setIconImage(icono);
        setLocationRelativeTo(null);
        setTitle("Fuente");
        dlmF = new DefaultListModel();
        dlmD = new DefaultListModel();
        dlmE = new DefaultListModel();
        fuentes = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
        listFuentes.setModel(dlmF);
        listDimension.setModel(dlmD);
        listEstilo.setModel(dlmE);
        listaF();
        listaD();
        listaE();
        setResizable(false);
    }

    public VtnConfiguracion getVtnConfig() {
        return vtnConfig;
    }

    public void setVtnConfig(VtnConfiguracion vtnConfig) {
        this.vtnConfig = vtnConfig;
    }

    public String getFuente() {
        return fuente;
    }

    public void setFuente(String fuente) {
        this.fuente = fuente;
    }

    public int getDimension() {
        return dimension;
    }

    public void setDimension(int dimension) {
        this.dimension = dimension;
    }

    public int getEstilo() {
        return estilo;
    }

    public void setEstilo(int estilo) {
        this.estilo = estilo;
    }

    private void listaF() {
        for (String fontF : fuentes) {
            dlmF.addElement(fontF);
        }

    }

    private void listaE() {
        dlmE.addElement("Normal");
        dlmE.addElement("Negrita");
        dlmE.addElement("Cursiva");
        dlmE.addElement("Cursiva y negrita");
    }

    private void listaD() {
        for (int i = 5; i < 30; i++) {
            dlmD.addElement(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        lblEstilo = new javax.swing.JLabel();
        lblFuente = new javax.swing.JLabel();
        lblTamanio = new javax.swing.JLabel();
        txtDimencion = new javax.swing.JTextField();
        txtEstilo = new javax.swing.JTextField();
        txtFuente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFuentes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDimension = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEstilo = new javax.swing.JList<>();
        pnlMuestra = new org.edisoncor.gui.panel.PanelRound();
        lblMuestra = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRestablecer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel1.setColorPrimario(new java.awt.Color(0, 51, 51));
        panel1.setColorSecundario(new java.awt.Color(0, 153, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEstilo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEstilo.setForeground(new java.awt.Color(255, 255, 255));
        lblEstilo.setText("Estilo:");
        panel1.add(lblEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, 20));

        lblFuente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblFuente.setText("Fuente:");
        panel1.add(lblFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 20));

        lblTamanio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTamanio.setForeground(new java.awt.Color(255, 255, 255));
        lblTamanio.setText("Tamaño:");
        panel1.add(lblTamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 60, 20));

        txtDimencion.setEditable(false);
        txtDimencion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDimencion.setFocusable(false);
        txtDimencion.setRequestFocusEnabled(false);
        panel1.add(txtDimencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 60, 20));

        txtEstilo.setEditable(false);
        txtEstilo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEstilo.setFocusable(false);
        txtEstilo.setRequestFocusEnabled(false);
        panel1.add(txtEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 110, 20));

        txtFuente.setEditable(false);
        txtFuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFuente.setFocusable(false);
        txtFuente.setRequestFocusEnabled(false);
        panel1.add(txtFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 20));

        listFuentes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "fuente1", "fuente2", "fuente3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listFuentes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listFuentes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFuentesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listFuentes);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 160));

        listDimension.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "10", "12", "14", "16" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDimension.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDimension.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDimensionValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listDimension);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 60, 160));

        listEstilo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "estilo1", "estilo2", "estilo3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listEstilo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listEstilo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEstiloValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listEstilo);

        panel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 110, 160));

        pnlMuestra.setColorDeBorde(new java.awt.Color(0, 102, 102));
        pnlMuestra.setColorPrimario(new java.awt.Color(255, 255, 255));
        pnlMuestra.setColorSecundario(new java.awt.Color(255, 255, 255));

        lblMuestra.setText("Hola, ¡No soy un robot!");

        javax.swing.GroupLayout pnlMuestraLayout = new javax.swing.GroupLayout(pnlMuestra);
        pnlMuestra.setLayout(pnlMuestraLayout);
        pnlMuestraLayout.setHorizontalGroup(
            pnlMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMuestraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMuestraLayout.setVerticalGroup(
            pnlMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMuestraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.add(pnlMuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 420, 90));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        btnRestablecer.setText("Reestablecer");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });
        panel1.add(btnRestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listFuentesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFuentesValueChanged
        fuente = listFuentes.getSelectedValue();
        txtFuente.setText(listFuentes.getSelectedValue());
        lblMuestra.setFont(new Font(fuente, estilo, dimension));
    }//GEN-LAST:event_listFuentesValueChanged

    private void listDimensionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDimensionValueChanged
        dimension = Integer.parseInt(String.valueOf(listDimension.getSelectedValue()));
        txtDimencion.setText(String.valueOf(listDimension.getSelectedValue()));
        lblMuestra.setFont(new Font(fuente, estilo, dimension));
    }//GEN-LAST:event_listDimensionValueChanged

    private void listEstiloValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEstiloValueChanged
        String cadena = lblMuestra.getText();
        //jLabel3.setEditable(true);
        if (listEstilo.getSelectedValue().toUpperCase().equals("NORMAL")) {
            estilo = 0;
        } else if (listEstilo.getSelectedValue().toUpperCase().equals("NEGRITA")) {
            estilo = 1;
            lblMuestra.setFont(new Font(fuente, estilo, dimension));
        } else if (listEstilo.getSelectedValue().toUpperCase().equals("CURSIVA")) {
            estilo = 2;
            lblMuestra.setFont(new Font(fuente, estilo, dimension));
        } else if (listEstilo.getSelectedValue().toUpperCase().equals("CURSIVA Y NEGRITA")) {
            estilo = 3;
            lblMuestra.setFont(new Font(fuente, estilo, dimension));
        }
        txtEstilo.setText(listEstilo.getSelectedValue());
        lblMuestra.setFont(new Font(fuente, estilo, dimension));
    }//GEN-LAST:event_listEstiloValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        listDimension.setSelectedValue(dimension, true);
        listEstilo.setSelectedIndex(estilo);

        for (int i = 0; i < dlmF.size(); i++) {
            if (dlmF.get(i).toString().toUpperCase().equals(fuente.toUpperCase())) {
                iFont = i;
            }
        }

        listFuentes.setSelectedIndex(iFont);
        lblTamanio.setFont(new Font(fuente, estilo, dimension));
    }//GEN-LAST:event_formWindowOpened

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        getVtnConfig().setFuente("Monospaced");
        getVtnConfig().setEstilo(0);
        getVtnConfig().setDimension(14);
        getVtnConfig().getTxtFuente().setText("Monospaced 14");
        this.dispose();
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        getVtnConfig().setFuente(fuente);
        getVtnConfig().setEstilo(estilo);
        getVtnConfig().setDimension(dimension);
        getVtnConfig().getTxtFuente().setText(fuente + " " + dimension);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnFuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnFuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnFuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnFuente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VtnFuente dialog = new VtnFuente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblFuente;
    private javax.swing.JLabel lblMuestra;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JList<String> listDimension;
    private javax.swing.JList<String> listEstilo;
    private javax.swing.JList<String> listFuentes;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelRound pnlMuestra;
    private javax.swing.JTextField txtDimencion;
    private javax.swing.JTextField txtEstilo;
    private javax.swing.JTextField txtFuente;
    // End of variables declaration//GEN-END:variables
}
